config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'search#index'

  resources :search, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe
  attr_accessor :title, :href, :ingredients, :thumbnail

  def initialize
    @title = ''
    @href = ''
    @ingredients = []
    @thumbnail = ''
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :application_title, :initialize_flash_messages

  private

  def initialize_flash_messages
    flash[:error] = []
    flash[:success] = []
  end

  def application_title
    @titles = ['Recipe Finder']
  end

  def is_production?
    Rails.env == 'production'
  end
end

app/controllers/concerns/recipe_puppy_api.rb
require "net/http"
require "uri"

class RecipePuppyAPI
  def initialize
    @host = 'http://www.recipepuppy.com/'
    @api_base = 'api/'
    @q = ''

    @uri = URI.parse "#{@host}#{@api_base}"
  end

  def retrieve_recipes params
    map_items(JSON.parse request(params))
  end

  def to_recipe item
    recipe = Recipe.new
    recipe.title = item['title']
    recipe.href = item['href']
    recipe.ingredients = item['ingredients'].split(', ')
    recipe.thumbnail = item['thumbnail']

    recipe
  end

  private

  def request params
    @uri.query = URI.encode_www_form params

    http = Net::HTTP.new(@uri.host, @uri.port)

    request = Net::HTTP::Get.new(@uri.request_uri)

    response = http.request request

    raise "API Server error. Try again later." unless response.code == '200'

    response.body
  end

  def map_items response_body
    response_body["results"].map { |item| to_recipe item }
  end
end

app/controllers/search_controller.rb
require 'will_paginate/array'

class SearchController < ApplicationController
  http_basic_authenticate_with name: RecipePuppyApi::Application.config.basic_auth_user, password: RecipePuppyApi::Application.config.basic_auth_password, if: :is_production?

  def index
    @titles.push 'Search'
    @items = []

    begin
      if params[:commit].present?
        @items = retrieve_items
        @items = @items.paginate(page: 1, per_page: RecipePuppyApi::Application.config.items_per_page) if @items.size > RecipePuppyApi::Application.config.items_per_page
      end
    rescue Exception => e
      flash[:error].push e.message
    end
  end

  private

  def retrieve_items
    puppy_api = RecipePuppyAPI.new
    puppy_api.retrieve_recipes(q: params[:q])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to 'Recipe finder', search_index_path, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title><%= @titles.join(' - ') %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <%= yield %>
    </div><!-- /.container -->
  </body>
</html>

app/views/search/index.html.haml
.mt-5.notifications
  - if flash[:error].present?
    .alert.alert-danger{ role: alert }
      - flash[:error].each do |msg|
        %p
          = msg

.mt-5.search-module
  = form_tag('/search', method: 'get') do
    .input-group
      = text_field_tag(:q, '', placeholder: 'Search for...', class: 'form-control')
      %span.input-group-btn
        = submit_tag("Search", class: 'btn btn-secondary')

  - if @items.empty?
    .mt-4.empty
      .alert.alert-secondary.text-center{ role: alert }
        No recipes in the list
  - else
    .mt-4.summary
      Total recipes in the list:
      %span.badge.badge-secondary
        = @items.count

    %table.mt-2.table.table-striped#results
      %tbody
        - @items.each do |item|
          %tr
            %td
              .thumbnail
                - if item.thumbnail.present?
                  %img{ src: item.thumbnail, alt: "No image" }
                - else
                  %img{ src: 'http://img.recipepuppy.com/9.jpg', alt: "No image" }
              .information
                %h6
                  %a{ href: item.href, target: '_blank' }
                    = raw item.title
                %p
                  %span.caption
                    Ingredients:
                  %span.ingredients
                    - item.ingredients.each do |ingredient|
                      %span.badget
                        = raw ingredient